# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# before:
#   hooks:
# You may remove this if you don't use go modules.
# - go mod tidy
# you may remove this if you don't need go generate
# - go generate ./...
builds:
  - binary: ivcap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
# archives:
#   - name_template: >-
#       {{ .ProjectName }}_
#       {{ .Tag }}_
#       {{- title .Os }}_
#       {{- if eq .Arch "amd64" }}x86_64
#       {{- else if eq .Arch "386" }}i386
#       {{- else }}{{ .Arch }}{{ end }}
brews:
  - name: ivcap
    homepage: "https://github.com/ivcap-works/ivcap-cli"
    repository:
      owner: ivcap-works
      name: homebrew-ivcap
    commit_author:
      name: maxott
      email: max.ott@data61.csiro.au

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
