# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# before:
#   hooks:
# You may remove this if you don't use go modules.
# - go mod tidy
# you may remove this if you don't need go generate
# - go generate ./...
builds:
  - id: ivcap
    binary: ivcap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - builds:
      - ivcap  # refers to the build id
    files:
      - doc/*.1
brews:
  - name: ivcap
    homepage: "https://github.com/ivcap-works/ivcap-cli"
    repository:
      owner: ivcap-works
      name: homebrew-ivcap
    commit_author:
      name: maxott
      email: max.ott@data61.csiro.au
    install: |
      bin.install "ivcap"
      man1.install Dir["doc/*.1"]
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
