// Package accountsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package accountsapi

// Account defines model for Account.
type Account struct {
	// Id Account URN
	Id string `json:"id"`

	// Kind personal | workspace
	Kind string `json:"kind"`

	// Name Display name
	Name string `json:"name"`
}

// AddAccountGrantPayload Request body for add-account-grant.
type AddAccountGrantPayload struct {
	// Capabilities Account capabilities: read, create_project, manage_members. The caller must hold each capability they grant.
	Capabilities []string `json:"capabilities"`

	// UserId User URN to grant capabilities to
	UserId string `json:"user_id"`
}

// AddProjectGrantPayload Request body for add-project-grant.
type AddProjectGrantPayload struct {
	// Capabilities Project capabilities: read, write, delete, add_user, remove_user, add_child_project. The caller must hold each capability they grant.
	Capabilities []string `json:"capabilities"`

	// PrincipalId Principal URN (for service: the m2m_clients.id, i.e. the session pseudonym)
	PrincipalId string `json:"principal_id"`

	// PrincipalKind user | service
	PrincipalKind string `json:"principal_kind"`
}

// BadRequestT bad request
type BadRequestT struct {
	// Message Error message
	Message string `json:"message"`
}

// CapabilitiesResult defines model for CapabilitiesResult.
type CapabilitiesResult struct {
	// Account Capabilities grantable on an account
	Account []Capability `json:"account"`

	// Project Capabilities grantable on a project
	Project []Capability `json:"project"`
}

// Capability defines model for Capability.
type Capability struct {
	// Description Human-readable description of what the capability allows
	Description *string `json:"description,omitempty"`

	// Name Capability name as used in grants and invitations
	Name string `json:"name"`
}

// ConflictT conflict
type ConflictT struct {
	// Message Error message
	Message string `json:"message"`
}

// CreateAccountInvitationPayload Request body for create-account-invitation.
type CreateAccountInvitationPayload struct {
	// Capabilities Elevated account capabilities to grant on accept (create_project, manage_members); omit for a read-only member. The inviter must hold each capability the invitation carries.
	Capabilities *[]string `json:"capabilities,omitempty"`

	// Email Invitee email address
	Email string `json:"email"`
}

// CreateAccountPayload Request body for create-account.
type CreateAccountPayload struct {
	// Name Display name for the new workspace account
	Name string `json:"name"`
}

// CreateInvitationPayload Request body for create-invitation.
type CreateInvitationPayload struct {
	// Capabilities Project capabilities to grant on accept. The inviter must hold each capability the invitation carries.
	Capabilities []string `json:"capabilities"`

	// Email Invitee email address
	Email string `json:"email"`
}

// CreateProjectPayload Request body for create-project.
type CreateProjectPayload struct {
	// AccountId Owning account URN. Optional when parent_id is given (defaults to the parent's account); required otherwise. When supplied it overrides the inherited account, and the caller must have can_create_project on it.
	AccountId *string `json:"account_id,omitempty"`

	// Name Display name for the new project
	Name string `json:"name"`

	// ParentId Optional parent project URN. The new project inherits this parent's account unless account_id overrides it. The caller must have can_add_child_project on the parent.
	ParentId *string `json:"parent_id,omitempty"`
}

// ForbiddenT forbidden
type ForbiddenT struct {
	// Message Error message
	Message string `json:"message"`
}

// Invitation defines model for Invitation.
type Invitation struct {
	// AccountId Account URN (set for account invitations)
	AccountId *string `json:"account_id,omitempty"`

	// Capabilities Capabilities the invite grants (project or account caps per kind)
	Capabilities []string `json:"capabilities"`

	// Email Invitee email (only on the inviter's create response / project listing)
	Email *string `json:"email,omitempty"`

	// ExpiresAt RFC3339 expiry
	ExpiresAt string `json:"expires_at"`

	// Id Invitation URN
	Id string `json:"id"`

	// Kind Invitation target kind: project | account
	Kind string `json:"kind"`

	// ProjectId Project URN (set for project invitations)
	ProjectId *string `json:"project_id,omitempty"`

	// Status pending | accepted | declined | revoked
	Status string `json:"status"`
}

// ListAccountsResult defines model for ListAccountsResult.
type ListAccountsResult struct {
	Accounts []Account `json:"accounts"`
}

// ListInvitationsResult defines model for ListInvitationsResult.
type ListInvitationsResult struct {
	Invitations []Invitation `json:"invitations"`
}

// ListMembersResult defines model for ListMembersResult.
type ListMembersResult struct {
	Members []MemberProfile `json:"members"`
}

// ListProjectsResult defines model for ListProjectsResult.
type ListProjectsResult struct {
	Projects []Project `json:"projects"`
}

// MemberProfile defines model for MemberProfile.
type MemberProfile struct {
	// Capabilities Granted capabilities on the object (project or account grants)
	Capabilities []string `json:"capabilities"`

	// DisplayName Display name (empty if not available)
	DisplayName string `json:"display_name"`

	// Email Email (empty if not available or service principal)
	Email string `json:"email"`

	// Kind user | service
	Kind string `json:"kind"`

	// UserId Principal URN
	UserId string `json:"user_id"`
}

// NotFoundT not found
type NotFoundT struct {
	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Message Error message
	Message string `json:"message"`
}

// Project defines model for Project.
type Project struct {
	// AccountId Owning account URN
	AccountId string `json:"account_id"`

	// Id Project URN
	Id string `json:"id"`

	// Kind personal | workspace
	Kind string `json:"kind"`

	// Name Display name
	Name string `json:"name"`

	// OwnerUserId Owner user URN (record of provenance)
	OwnerUserId string `json:"owner_user_id"`

	// ParentId Parent project URN, if any
	ParentId *string `json:"parent_id,omitempty"`
}

// UnauthorizedT not authorized
type UnauthorizedT struct {
	// Message Error message
	Message string `json:"message"`
}

// UpdateProjectPayload Request body for update-project.
type UpdateProjectPayload struct {
	// Name New display name
	Name string `json:"name"`
}

// AccountsRemoveAccountGrantParams defines parameters for AccountsRemoveAccountGrant.
type AccountsRemoveAccountGrantParams struct {
	// Capability Account capability to revoke
	Capability string `form:"capability" json:"capability"`
}

// AccountsRemoveProjectGrantParams defines parameters for AccountsRemoveProjectGrant.
type AccountsRemoveProjectGrantParams struct {
	// PrincipalKind user | service
	PrincipalKind string `form:"principal_kind" json:"principal_kind"`

	// Capability Project capability to revoke
	Capability string `form:"capability" json:"capability"`
}

// AccountsRemoveProjectMemberParams defines parameters for AccountsRemoveProjectMember.
type AccountsRemoveProjectMemberParams struct {
	// PrincipalKind user | service
	PrincipalKind string `form:"principal_kind" json:"principal_kind"`
}

// AccountsCreateAccountJSONRequestBody defines body for AccountsCreateAccount for application/json ContentType.
type AccountsCreateAccountJSONRequestBody = CreateAccountPayload

// AccountsCreateAccountInvitationJSONRequestBody defines body for AccountsCreateAccountInvitation for application/json ContentType.
type AccountsCreateAccountInvitationJSONRequestBody = CreateAccountInvitationPayload

// AccountsAddAccountGrantJSONRequestBody defines body for AccountsAddAccountGrant for application/json ContentType.
type AccountsAddAccountGrantJSONRequestBody = AddAccountGrantPayload

// AccountsCreateProjectJSONRequestBody defines body for AccountsCreateProject for application/json ContentType.
type AccountsCreateProjectJSONRequestBody = CreateProjectPayload

// AccountsUpdateProjectJSONRequestBody defines body for AccountsUpdateProject for application/json ContentType.
type AccountsUpdateProjectJSONRequestBody = UpdateProjectPayload

// AccountsAddProjectGrantJSONRequestBody defines body for AccountsAddProjectGrant for application/json ContentType.
type AccountsAddProjectGrantJSONRequestBody = AddProjectGrantPayload

// AccountsCreateInvitationJSONRequestBody defines body for AccountsCreateInvitation for application/json ContentType.
type AccountsCreateInvitationJSONRequestBody = CreateInvitationPayload
