// Package accountsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package accountsapi

const (
	Jwt_header_AuthorizationScopes        = "jwt_header_Authorization.Scopes"
	Onboarding_header_AuthorizationScopes = "onboarding_header_Authorization.Scopes"
)

// Account defines model for Account.
type Account struct {
	// Id Account URN
	Id string `json:"id"`

	// Kind personal | org
	Kind string `json:"kind"`

	// Name Display name
	Name string `json:"name"`
}

// AddAccountGrantPayload defines model for AddAccountGrantPayload.
type AddAccountGrantPayload struct {
	// Capabilities Account capabilities: read, create_project, manage_members
	Capabilities []string `json:"capabilities"`

	// Id Account URN
	Id string `json:"id"`

	// Token Identity-scoped JWT
	Token *string `json:"token,omitempty"`

	// UserId User URN to grant capabilities to
	UserId string `json:"user_id"`
}

// AddAccountGrantPayload2 defines model for AddAccountGrantPayload2.
type AddAccountGrantPayload2 struct {
	// Capabilities Account capabilities: read, create_project, manage_members
	Capabilities []string `json:"capabilities"`

	// UserId User URN to grant capabilities to
	UserId string `json:"user_id"`
}

// AddProjectGrantPayload defines model for AddProjectGrantPayload.
type AddProjectGrantPayload struct {
	// Capabilities Project capabilities: read, write, delete, add_user, remove_user
	Capabilities []string `json:"capabilities"`

	// PrincipalId Principal URN (for service: the m2m_clients.id, i.e. the session pseudonym)
	PrincipalId string `json:"principal_id"`

	// PrincipalKind user | service
	PrincipalKind string `json:"principal_kind"`

	// ProjectId Project URN
	ProjectId string `json:"project_id"`

	// Token JWT
	Token *string `json:"token,omitempty"`
}

// AddProjectGrantPayload2 defines model for AddProjectGrantPayload2.
type AddProjectGrantPayload2 struct {
	// Capabilities Project capabilities: read, write, delete, add_user, remove_user
	Capabilities []string `json:"capabilities"`

	// PrincipalId Principal URN (for service: the m2m_clients.id, i.e. the session pseudonym)
	PrincipalId string `json:"principal_id"`

	// PrincipalKind user | service
	PrincipalKind string `json:"principal_kind"`
}

// BadRequestT defines model for BadRequestT.
type BadRequestT struct {
	// Message Error message
	Message string `json:"message"`
}

// CapabilitiesResult defines model for CapabilitiesResult.
type CapabilitiesResult struct {
	// Account Capabilities grantable on an account
	Account []Capability `json:"account"`

	// Project Capabilities grantable on a project
	Project []Capability `json:"project"`
}

// Capability defines model for Capability.
type Capability struct {
	// Description Human-readable description of what the capability allows
	Description *string `json:"description,omitempty"`

	// Name Capability name as used in grants and invitations
	Name string `json:"name"`
}

// ConflictT defines model for ConflictT.
type ConflictT struct {
	// Message Error message
	Message *string `json:"message,omitempty"`
}

// CreateAccountInvitationPayload defines model for CreateAccountInvitationPayload.
type CreateAccountInvitationPayload struct {
	// AccountId Account URN
	AccountId string `json:"account_id"`

	// Capabilities Elevated account capabilities to grant on accept (create_project, manage_members); omit for a read-only member
	Capabilities *[]string `json:"capabilities,omitempty"`

	// Email Invitee email address
	Email string `json:"email"`

	// Token JWT
	Token *string `json:"token,omitempty"`
}

// CreateAccountInvitationPayload2 defines model for CreateAccountInvitationPayload2.
type CreateAccountInvitationPayload2 struct {
	// Capabilities Elevated account capabilities to grant on accept (create_project, manage_members); omit for a read-only member
	Capabilities *[]string `json:"capabilities,omitempty"`

	// Email Invitee email address
	Email string `json:"email"`
}

// CreateAccountPayload defines model for CreateAccountPayload.
type CreateAccountPayload struct {
	// Name Display name for the new org account
	Name string `json:"name"`

	// Token Identity-scoped JWT
	Token *string `json:"token,omitempty"`
}

// CreateAccountPayload2 defines model for CreateAccountPayload2.
type CreateAccountPayload2 struct {
	// Name Display name for the new org account
	Name string `json:"name"`
}

// CreateInvitationPayload defines model for CreateInvitationPayload.
type CreateInvitationPayload struct {
	// Capabilities Project capabilities to grant on accept
	Capabilities []string `json:"capabilities"`

	// Email Invitee email address
	Email string `json:"email"`

	// ProjectId Project URN
	ProjectId string `json:"project_id"`

	// Token JWT
	Token *string `json:"token,omitempty"`
}

// CreateInvitationPayload2 defines model for CreateInvitationPayload2.
type CreateInvitationPayload2 struct {
	// Capabilities Project capabilities to grant on accept
	Capabilities []string `json:"capabilities"`

	// Email Invitee email address
	Email string `json:"email"`
}

// CreateProjectPayload defines model for CreateProjectPayload.
type CreateProjectPayload struct {
	// AccountId Owning account URN. Optional when parent_id is given (defaults to the parent's account); required otherwise. When supplied it overrides the inherited account, and the caller must have can_create_project on it.
	AccountId *string `json:"account_id,omitempty"`

	// Name Display name for the new project
	Name string `json:"name"`

	// ParentId Optional parent project URN. The new project inherits this parent's account unless account_id overrides it.
	ParentId *string `json:"parent_id,omitempty"`

	// Token Identity-scoped JWT
	Token *string `json:"token,omitempty"`
}

// CreateProjectPayload2 defines model for CreateProjectPayload2.
type CreateProjectPayload2 struct {
	// AccountId Owning account URN. Optional when parent_id is given (defaults to the parent's account); required otherwise. When supplied it overrides the inherited account, and the caller must have can_create_project on it.
	AccountId *string `json:"account_id,omitempty"`

	// Name Display name for the new project
	Name string `json:"name"`

	// ParentId Optional parent project URN. The new project inherits this parent's account unless account_id overrides it.
	ParentId *string `json:"parent_id,omitempty"`
}

// DeleteProjectPayload defines model for DeleteProjectPayload.
type DeleteProjectPayload struct {
	// Id Project URN
	Id string `json:"id"`

	// Token JWT
	Token *string `json:"token,omitempty"`
}

// EnsureOnboardingPayload defines model for EnsureOnboardingPayload.
type EnsureOnboardingPayload struct {
	// AccountId Personal account URN (adopted from ivcap-id)
	AccountId string `json:"account_id"`

	// Email Verified email, or empty if unverified/absent
	Email *string `json:"email,omitempty"`

	// EmailVerified Whether the upstream IdP asserts email_verified
	EmailVerified *bool `json:"email_verified,omitempty"`

	// Key Onboarding shared secret
	Key *string `json:"key,omitempty"`

	// Name Display name from identity provider traits
	Name *string `json:"name,omitempty"`

	// UserId User URN
	UserId string `json:"user_id"`
}

// EnsureOnboardingPayload2 defines model for EnsureOnboardingPayload2.
type EnsureOnboardingPayload2 struct {
	// AccountId Personal account URN (adopted from ivcap-id)
	AccountId string `json:"account_id"`

	// Email Verified email, or empty if unverified/absent
	Email *string `json:"email,omitempty"`

	// EmailVerified Whether the upstream IdP asserts email_verified
	EmailVerified *bool `json:"email_verified,omitempty"`

	// Name Display name from identity provider traits
	Name *string `json:"name,omitempty"`

	// UserId User URN
	UserId string `json:"user_id"`
}

// EnsureOnboardingResult defines model for EnsureOnboardingResult.
type EnsureOnboardingResult struct {
	// AccountId Personal account URN
	AccountId string `json:"account_id"`

	// BoundInvitations Number of pending invitations bound to this user
	BoundInvitations int64 `json:"bound_invitations"`

	// PersonalProjectId Personal project URN
	PersonalProjectId string `json:"personal_project_id"`
}

// ForbiddenT defines model for ForbiddenT.
type ForbiddenT struct {
	// Message Error message
	Message *string `json:"message,omitempty"`
}

// GetAccountPayload defines model for GetAccountPayload.
type GetAccountPayload struct {
	// Id Account URN
	Id string `json:"id"`

	// Token Identity-scoped JWT
	Token *string `json:"token,omitempty"`
}

// GetProjectPayload defines model for GetProjectPayload.
type GetProjectPayload struct {
	// Id Project URN
	Id string `json:"id"`

	// Token Identity-scoped or project-scoped JWT
	Token *string `json:"token,omitempty"`
}

// Invitation defines model for Invitation.
type Invitation struct {
	// AccountId Account URN (set for account invitations)
	AccountId *string `json:"account_id,omitempty"`

	// Capabilities Capabilities the invite grants (project or account caps per kind)
	Capabilities []string `json:"capabilities"`

	// Email Invitee email (only on the inviter's create response / project listing)
	Email *string `json:"email,omitempty"`

	// ExpiresAt RFC3339 expiry
	ExpiresAt string `json:"expires_at"`

	// Id Invitation URN
	Id string `json:"id"`

	// Kind Invitation target kind: project | account
	Kind string `json:"kind"`

	// ProjectId Project URN (set for project invitations)
	ProjectId *string `json:"project_id,omitempty"`

	// Status pending | accepted | declined | revoked
	Status string `json:"status"`
}

// InvitationIDPayload defines model for InvitationIDPayload.
type InvitationIDPayload struct {
	// Id Invitation URN
	Id string `json:"id"`

	// Token Identity-scoped JWT of the invitee
	Token *string `json:"token,omitempty"`
}

// LeaveProjectPayload defines model for LeaveProjectPayload.
type LeaveProjectPayload struct {
	// Id Project URN
	Id string `json:"id"`

	// Token JWT
	Token *string `json:"token,omitempty"`
}

// ListAccountInvitationsPayload defines model for ListAccountInvitationsPayload.
type ListAccountInvitationsPayload struct {
	// AccountId Account URN
	AccountId string `json:"account_id"`

	// Token JWT
	Token *string `json:"token,omitempty"`
}

// ListAccountMembersPayload defines model for ListAccountMembersPayload.
type ListAccountMembersPayload struct {
	// Id Account URN
	Id string `json:"id"`

	// Token Identity-scoped JWT
	Token *string `json:"token,omitempty"`
}

// ListAccountProjectsPayload defines model for ListAccountProjectsPayload.
type ListAccountProjectsPayload struct {
	// Id Account URN
	Id string `json:"id"`

	// Token Identity-scoped JWT
	Token *string `json:"token,omitempty"`
}

// ListAccountsResult defines model for ListAccountsResult.
type ListAccountsResult struct {
	Accounts []Account `json:"accounts"`
}

// ListInvitationsResult defines model for ListInvitationsResult.
type ListInvitationsResult struct {
	Invitations []Invitation `json:"invitations"`
}

// ListMembersResult defines model for ListMembersResult.
type ListMembersResult struct {
	Members []MemberProfile `json:"members"`
}

// ListMyInvitationsPayload defines model for ListMyInvitationsPayload.
type ListMyInvitationsPayload struct {
	// Token Identity-scoped JWT of the invitee
	Token *string `json:"token,omitempty"`
}

// ListProjectInvitationsPayload defines model for ListProjectInvitationsPayload.
type ListProjectInvitationsPayload struct {
	// ProjectId Project URN
	ProjectId string `json:"project_id"`

	// Token JWT
	Token *string `json:"token,omitempty"`
}

// ListProjectMembersPayload defines model for ListProjectMembersPayload.
type ListProjectMembersPayload struct {
	// Id Project URN
	Id string `json:"id"`

	// Token JWT
	Token *string `json:"token,omitempty"`
}

// ListProjectsResult defines model for ListProjectsResult.
type ListProjectsResult struct {
	Projects []Project `json:"projects"`
}

// MemberProfile defines model for MemberProfile.
type MemberProfile struct {
	// Capabilities Granted capabilities on the object (project or account grants)
	Capabilities []string `json:"capabilities"`

	// DisplayName Display name (empty if not available)
	DisplayName string `json:"display_name"`

	// Email Email (empty if not available or service principal)
	Email string `json:"email"`

	// Kind user | service
	Kind string `json:"kind"`

	// UserId Principal URN
	UserId string `json:"user_id"`
}

// NotFoundT defines model for NotFoundT.
type NotFoundT struct {
	// Id Resource identifier
	Id *string `json:"id,omitempty"`

	// Message Error message
	Message *string `json:"message,omitempty"`
}

// Project defines model for Project.
type Project struct {
	// AccountId Owning account URN
	AccountId string `json:"account_id"`

	// Id Project URN
	Id string `json:"id"`

	// Kind personal | org
	Kind string `json:"kind"`

	// Name Display name
	Name string `json:"name"`

	// OwnerUserId Owner user URN (record of provenance)
	OwnerUserId string `json:"owner_user_id"`

	// ParentId Parent project URN, if any
	ParentId *string `json:"parent_id,omitempty"`
}

// RemoveAccountGrantPayload defines model for RemoveAccountGrantPayload.
type RemoveAccountGrantPayload struct {
	// Capability Account capability to revoke
	Capability string `json:"capability"`

	// Id Account URN
	Id string `json:"id"`

	// Token Identity-scoped JWT
	Token *string `json:"token,omitempty"`

	// UserId User URN
	UserId string `json:"user_id"`
}

// RemoveAccountMemberPayload defines model for RemoveAccountMemberPayload.
type RemoveAccountMemberPayload struct {
	// Id Account URN
	Id string `json:"id"`

	// Token Identity-scoped JWT
	Token *string `json:"token,omitempty"`

	// UserId User URN to remove
	UserId string `json:"user_id"`
}

// RemoveProjectGrantPayload defines model for RemoveProjectGrantPayload.
type RemoveProjectGrantPayload struct {
	// Capability Project capability to revoke
	Capability string `json:"capability"`

	// PrincipalId Principal URN
	PrincipalId string `json:"principal_id"`

	// PrincipalKind user | service
	PrincipalKind string `json:"principal_kind"`

	// ProjectId Project URN
	ProjectId string `json:"project_id"`

	// Token JWT
	Token *string `json:"token,omitempty"`
}

// RemoveProjectMemberPayload defines model for RemoveProjectMemberPayload.
type RemoveProjectMemberPayload struct {
	// PrincipalId Principal URN
	PrincipalId string `json:"principal_id"`

	// PrincipalKind user | service
	PrincipalKind string `json:"principal_kind"`

	// ProjectId Project URN
	ProjectId string `json:"project_id"`

	// Token JWT
	Token *string `json:"token,omitempty"`
}

// ResyncPayload defines model for ResyncPayload.
type ResyncPayload struct {
	// Id Object URN to resync FGA tuples for
	Id string `json:"id"`

	// Key Onboarding shared secret
	Key *string `json:"key,omitempty"`

	// Kind project | account
	Kind string `json:"kind"`
}

// ResyncPayload2 defines model for ResyncPayload2.
type ResyncPayload2 struct {
	// Id Object URN to resync FGA tuples for
	Id string `json:"id"`

	// Kind project | account
	Kind string `json:"kind"`
}

// RevokeInvitationPayload defines model for RevokeInvitationPayload.
type RevokeInvitationPayload struct {
	// Id Invitation URN
	Id string `json:"id"`

	// Token JWT
	Token *string `json:"token,omitempty"`
}

// RevokePrincipalPayload defines model for RevokePrincipalPayload.
type RevokePrincipalPayload struct {
	// Id Principal URN being offboarded
	Id string `json:"id"`

	// Key Onboarding shared secret
	Key *string `json:"key,omitempty"`

	// Kind user | service
	Kind string `json:"kind"`
}

// RevokePrincipalPayload2 defines model for RevokePrincipalPayload2.
type RevokePrincipalPayload2 struct {
	// Id Principal URN being offboarded
	Id string `json:"id"`

	// Kind user | service
	Kind string `json:"kind"`
}

// UnauthorizedT defines model for UnauthorizedT.
type UnauthorizedT struct {
	// Message Error message
	Message *string `json:"message,omitempty"`
}

// UpdateProjectPayload defines model for UpdateProjectPayload.
type UpdateProjectPayload struct {
	// Id Project URN
	Id string `json:"id"`

	// Name New display name
	Name string `json:"name"`

	// Token JWT
	Token *string `json:"token,omitempty"`
}

// UpdateProjectPayload2 defines model for UpdateProjectPayload2.
type UpdateProjectPayload2 struct {
	// Name New display name
	Name string `json:"name"`
}

// AccountsRemoveAccountGrantParams defines parameters for AccountsRemoveAccountGrant.
type AccountsRemoveAccountGrantParams struct {
	// Capability Account capability to revoke
	Capability string `form:"capability" json:"capability"`
}

// AccountsRemoveProjectGrantParams defines parameters for AccountsRemoveProjectGrant.
type AccountsRemoveProjectGrantParams struct {
	// PrincipalKind user | service
	PrincipalKind string `form:"principal_kind" json:"principal_kind"`

	// Capability Project capability to revoke
	Capability string `form:"capability" json:"capability"`
}

// AccountsRemoveProjectMemberParams defines parameters for AccountsRemoveProjectMember.
type AccountsRemoveProjectMemberParams struct {
	// PrincipalKind user | service
	PrincipalKind string `form:"principal_kind" json:"principal_kind"`
}

// AccountsCreateAccountJSONRequestBody defines body for AccountsCreateAccount for application/json ContentType.
type AccountsCreateAccountJSONRequestBody = CreateAccountPayload2

// AccountsCreateAccountInvitationJSONRequestBody defines body for AccountsCreateAccountInvitation for application/json ContentType.
type AccountsCreateAccountInvitationJSONRequestBody = CreateAccountInvitationPayload2

// AccountsAddAccountGrantJSONRequestBody defines body for AccountsAddAccountGrant for application/json ContentType.
type AccountsAddAccountGrantJSONRequestBody = AddAccountGrantPayload2

// AccountsEnsureOnboardingJSONRequestBody defines body for AccountsEnsureOnboarding for application/json ContentType.
type AccountsEnsureOnboardingJSONRequestBody = EnsureOnboardingPayload2

// AccountsRevokePrincipalJSONRequestBody defines body for AccountsRevokePrincipal for application/json ContentType.
type AccountsRevokePrincipalJSONRequestBody = RevokePrincipalPayload2

// AccountsResyncJSONRequestBody defines body for AccountsResync for application/json ContentType.
type AccountsResyncJSONRequestBody = ResyncPayload2

// AccountsCreateProjectJSONRequestBody defines body for AccountsCreateProject for application/json ContentType.
type AccountsCreateProjectJSONRequestBody = CreateProjectPayload2

// AccountsUpdateProjectJSONRequestBody defines body for AccountsUpdateProject for application/json ContentType.
type AccountsUpdateProjectJSONRequestBody = UpdateProjectPayload2

// AccountsAddProjectGrantJSONRequestBody defines body for AccountsAddProjectGrant for application/json ContentType.
type AccountsAddProjectGrantJSONRequestBody = AddProjectGrantPayload2

// AccountsCreateInvitationJSONRequestBody defines body for AccountsCreateInvitation for application/json ContentType.
type AccountsCreateInvitationJSONRequestBody = CreateInvitationPayload2
