// Copyright 2023 Commonwealth Scientific and Industrial Research Organisation (CSIRO) ABN 41 687 119 230
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	humanize "github.com/dustin/go-humanize"
	"github.com/jedib0t/go-pretty/v6/table"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	adpt "github.com/ivcap-works/ivcap-cli/pkg/adapter"

	log "go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

const (
	ENV_PREFIX = "IVCAP"
	URN_PREFIX = "ivcap"
)

const RELEASE_CHECK_URL = "https://github.com/ivcap-works/ivcap-cli/releases/latest"

// Max characters to limit name to
const MAX_NAME_COL_LEN = 30

var ACCESS_TOKEN_ENV = ENV_PREFIX + "_ACCESS_TOKEN"

// flags
var (
	contextName         string
	accessToken         string
	accessTokenF        string
	accessTokenProvided bool
	timeout             int
	debug               bool
	agentContextFlag    bool
	agentHelpFlag       bool
)

var logger *log.Logger

type Config struct {
	Version       string    `yaml:"version"`
	ActiveContext string    `yaml:"active-context"`
	Contexts      []Context `yaml:"contexts"`
}

type Context struct {
	ApiVersion int    `yaml:"api-version"`
	Name       string `yaml:"name"`
	URL        string `yaml:"url"`
	AccountID  string `yaml:"account-id"`
	ProviderID string `yaml:"provider-id"`
	Host       string `yaml:"host"` // set Host header if necessary

	// User Information
	AccountName     string `yaml:"account-name"`
	AccountNickName string `yaml:"account-nickname"`
	Email           string `yaml:"email"`

	// Cached Credentials
	AccessToken       string    `yaml:"access-token"`
	AccessTokenExpiry time.Time `yaml:"access-token-expiry"`
	RefreshToken      string    `yaml:"refresh-token"`
}

type AppError struct {
	msg string
}

func (e *AppError) Error() string { return fmt.Sprintf("ERROR: %s", e.msg) }

var rootCmd = &cobra.Command{
	Use:   "ivcap",
	Short: "A command line tool to interact with a IVCAP deployment",
	Long: `A command line tool to to more conveniently interact with the
API exposed by a specific IVCAP deployment.`,
	RunE: func(cmd *cobra.Command, _ []string) error {
		// Root command invoked without a subcommand.
		// Allow a single-shot agent entrypoint for retrieving embedded guidance.
		if agentContextFlag || agentHelpFlag {
			return runAgentContext(cmd)
		}
		return cmd.Help()
	},
}

const agentSupportGroupID = "agent-support"
const coreCommandsGroupID = "core-commands"
const generalSupportGroupID = "general-support"

func Execute(version string) {
	rootCmd.Version = version
	rootCmd.SilenceUsage = true
	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
	if err := saveHistory(); err != nil {
		os.Exit(1)
	}
}

// docFix pairs a compiled regex with its replacement template (supports $1/$2 backrefs).
type docFix struct {
	pattern     *regexp.Regexp
	replacement []byte
}

func CreateDoc() {
	initLogger()

	// Ensure output directories exist.
	for _, dir := range []string{"./docs", "./man"} {
		// #nosec G301 - docs directories should be world-readable.
		if err := os.MkdirAll(dir, 0755); err != nil {
			logger.Fatal("while creating directory", log.String("dir", dir), log.Error(err))
		}
	}

	// Generate markdown command reference into ./docs.
	err := doc.GenMarkdownTree(rootCmd, "./docs")
	if err != nil {
		logger.Fatal("while creating markdown docs", log.Error(err))
	}

	// Generate man pages into ./man.
	header := &doc.GenManHeader{
		Title: "IVCAP",
		// Man section: 1 = general commands, 8 = admin commands, 3 = library calls.
		// This is a human-facing CLI, so section 1 is the most appropriate.
		Section: "1",
	}
	err = doc.GenManTree(rootCmd, header, "./man")
	if err != nil {
		logger.Fatal("while creating man pages", log.Error(err))
	}

	// Markdown: replace the auto-generated footer date with a fixed placeholder
	// so the line never triggers a git diff. (The Makefile also strips this line.)
	mdFixes := []docFix{
		{
			pattern:     regexp.MustCompile(`(?m)^###### Auto generated by spf13/cobra on .*$`),
			replacement: []byte("###### Auto generated by spf13/cobra on 1-Jan-2024"),
		},
	}
	if err := normalizeDocTimestamps("./docs", map[string]bool{".md": true}, mdFixes); err != nil {
		logger.Fatal("while normalizing doc timestamps", log.String("dir", "./docs"), log.Error(err))
	}

	// Man pages: cobra stamps the build date in two places:
	//   .TH "IVCAP" "1" "Jun 2026" "Auto generated by spf13/cobra" ""
	//   26-Jun-2026 Auto generated by spf13/cobra
	// Restore the committed file when only those dates changed so that git only
	// shows a diff when commands/flags/descriptions actually change.
	manDatePatterns := []*regexp.Regexp{
		regexp.MustCompile(`(?m)^\.TH "[^"]*" "[^"]*" "[^"]*".*$`),
		regexp.MustCompile(`(?m)^\d+-[A-Za-z]+-\d+ Auto generated by spf13/cobra$`),
	}
	if err := restoreManPagesIfUnchanged("./man", manDatePatterns); err != nil {
		logger.Fatal("while normalizing man page timestamps", log.String("dir", "./man"), log.Error(err))
	}
}

// normalizeDocTimestamps replaces auto-generated cobra timestamps in documentation
// files with a fixed date string so that files are only considered changed in git
// when their actual content changes, not just the build date.
//
// It uses root-scoped file handles (os.OpenRoot) to prevent path traversal and
// symlink TOCTOU races (gosec G304, G703, G122).
func normalizeDocTimestamps(dir string, exts map[string]bool, fixes []docFix) error {
	// Open a root-scoped handle for the directory.
	docRoot, rootErr := os.OpenRoot(dir)
	if rootErr != nil {
		return fmt.Errorf("while opening doc root %s: %w", dir, rootErr)
	}
	defer func() {
		if err := docRoot.Close(); err != nil {
			logger.Error("while closing doc root", log.String("dir", dir), log.Error(err))
		}
	}()

	return filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil // Skip directories
		}
		if !exts[filepath.Ext(path)] {
			return nil
		}

		relPath, relErr := filepath.Rel(dir, path)
		if relErr != nil {
			return fmt.Errorf("while computing rel path for %s: %w", path, relErr)
		}

		// Root-scoped read (prevents G304 / G122).
		rf, err := docRoot.Open(relPath)
		if err != nil {
			return fmt.Errorf("while reading %s: %w", path, err)
		}
		content, readErr := io.ReadAll(rf)
		if closeErr := rf.Close(); closeErr != nil && readErr == nil {
			readErr = closeErr
		}
		if readErr != nil {
			return fmt.Errorf("while reading %s: %w", path, readErr)
		}

		// Apply all fixes in sequence.
		updated := content
		for _, fix := range fixes {
			updated = fix.pattern.ReplaceAll(updated, fix.replacement)
		}

		// Only write if content changed.
		if string(updated) == string(content) {
			return nil
		}

		info, infoErr := d.Info()
		if infoErr != nil {
			return fmt.Errorf("while stat %s: %w", path, infoErr)
		}
		// Root-scoped write (prevents G703 / G122).
		wf, werr := docRoot.OpenFile(relPath, os.O_WRONLY|os.O_TRUNC, info.Mode())
		if werr != nil {
			return fmt.Errorf("while writing %s: %w", path, werr)
		}
		_, werr = wf.Write(updated)
		if closeErr := wf.Close(); closeErr != nil && werr == nil {
			werr = closeErr
		}
		return werr
	})
}

// restoreManPagesIfUnchanged compares each newly-generated man page against the
// version committed in git (HEAD). If the only differences are the auto-generated
// date fields, the committed file is restored so that git sees no change.
// When real content changes (new flags, descriptions, etc.) the newly generated
// file – with its up-to-date build date – is kept as-is.
func restoreManPagesIfUnchanged(dir string, datePatterns []*regexp.Regexp) error {
	docRoot, rootErr := os.OpenRoot(dir)
	if rootErr != nil {
		return fmt.Errorf("opening %s: %w", dir, rootErr)
	}
	defer func() {
		if err := docRoot.Close(); err != nil {
			logger.Error("while closing doc root", log.String("dir", dir), log.Error(err))
		}
	}()

	return filepath.WalkDir(dir, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil || d.IsDir() {
			return walkErr
		}
		ext := filepath.Ext(path)
		if ext != ".1" && ext != ".3" {
			return nil
		}

		relPath, relErr := filepath.Rel(dir, path)
		if relErr != nil {
			return relErr
		}

		// Read the newly generated content (root-scoped, prevents G304/G122).
		rf, err := docRoot.Open(relPath)
		if err != nil {
			return fmt.Errorf("reading %s: %w", path, err)
		}
		newContent, readErr := io.ReadAll(rf)
		if closeErr := rf.Close(); closeErr != nil && readErr == nil {
			readErr = closeErr
		}
		if readErr != nil {
			return fmt.Errorf("reading %s: %w", path, readErr)
		}

		// Fetch the committed version from git (HEAD).
		// #nosec G204 - path comes from filepath.WalkDir, not user input.
		committedContent, gitErr := exec.Command("git", "show", "HEAD:"+path).Output()
		if gitErr != nil {
			// File is new (not yet committed) – keep the generated version.
			return nil
		}

		// Strip the date-only fields from both copies and compare the rest.
		if bytes.Equal(stripDateFields(newContent, datePatterns), stripDateFields(committedContent, datePatterns)) {
			// Only dates differ → restore the committed file so git sees no diff.
			info, infoErr := d.Info()
			if infoErr != nil {
				return fmt.Errorf("stat %s: %w", path, infoErr)
			}
			// Root-scoped write (prevents G703/G122).
			wf, werr := docRoot.OpenFile(relPath, os.O_WRONLY|os.O_TRUNC, info.Mode())
			if werr != nil {
				return fmt.Errorf("writing %s: %w", path, werr)
			}
			_, werr = wf.Write(committedContent)
			if closeErr := wf.Close(); closeErr != nil && werr == nil {
				werr = closeErr
			}
			return werr
		}
		// Real content changed → keep the newly generated file (with its real date).
		return nil
	})
}

// stripDateFields removes auto-generated date fields from man page content so
// that two versions can be compared purely on their meaningful content.
func stripDateFields(content []byte, patterns []*regexp.Regexp) []byte {
	result := content
	for _, p := range patterns {
		result = p.ReplaceAll(result, []byte(""))
	}
	return result
}

const DEFAULT_SERVICE_TIMEOUT_IN_SECONDS = 30

func init() {
	cobra.OnInitialize(initConfig)

	// Group agent-facing commands separately in `ivcap --help` output.
	rootCmd.AddGroup(
		&cobra.Group{ID: coreCommandsGroupID, Title: "Commands:"},
		&cobra.Group{ID: agentSupportGroupID, Title: "Agent support commands:"},
		&cobra.Group{ID: generalSupportGroupID, Title: "General support commands:"},
	)

	// Ensure the primary (human) commands appear first in `ivcap --help`.
	// Any top-level command without an explicit GroupID is considered a core
	// command and placed into the `core-commands` group.
	defaultHelpFunc := rootCmd.HelpFunc()
	rootCmd.SetHelpFunc(func(cmd *cobra.Command, args []string) {
		if cmd == rootCmd {
			for _, c := range rootCmd.Commands() {
				switch c.Name() {
				case "help", "completion":
					c.GroupID = generalSupportGroupID
				default:
					if c.GroupID == "" {
						c.GroupID = coreCommandsGroupID
					}
				}
			}
		}
		defaultHelpFunc(cmd, args)
	})

	rootCmd.PersistentFlags().StringVar(&contextName, "context", "", "Context (deployment) to use")
	rootCmd.PersistentFlags().StringVar(&accessTokenF, "access-token", "",
		fmt.Sprintf("Access token to use for authentication with API server [%s]", ACCESS_TOKEN_ENV))
	rootCmd.PersistentFlags().IntVar(&timeout, "timeout", DEFAULT_SERVICE_TIMEOUT_IN_SECONDS, "Max. number of seconds to wait for completion")
	rootCmd.PersistentFlags().BoolVar(&debug, "debug", false, "Set logging level to DEBUG")
	rootCmd.PersistentFlags().StringVarP(&outputFormat, "output", "o", "", "Set format for displaying output [json, yaml]")
	rootCmd.PersistentFlags().BoolVar(&silent, "silent", false, "Do not show any progress information")
	rootCmd.PersistentFlags().BoolVar(&noHistory, "no-history", false, "Do not store history")
	rootCmd.PersistentFlags().BoolVar(&agentContextFlag, "agent-context", false, "Print embedded agent context guidance and exit")
	rootCmd.PersistentFlags().BoolVar(&agentHelpFlag, "agent-help", false, "Alias for --agent-context")
	// Keep agent retrieval available, but avoid cluttering human `--help` flag output.
	cobra.CheckErr(rootCmd.PersistentFlags().MarkHidden("agent-context"))
	cobra.CheckErr(rootCmd.PersistentFlags().MarkHidden("agent-help"))
}

// initConfig reads in config file and ENV variables if set.
func initConfig() {
	initLogger()
	// before proceeding, let's check for updates
	checkForUpdates(rootCmd.Version)
}

func initLogger() {
	cfg := log.NewDevelopmentConfig()
	// cfg := zap.NewProductionConfig()
	cfg.OutputPaths = []string{"stdout"}

	logLevel := zapcore.ErrorLevel
	if debug {
		logLevel = zapcore.DebugLevel
	}
	cfg.Level = log.NewAtomicLevelAt(logLevel)
	logger, err := cfg.Build()
	if err != nil {
		panic(err)
	}

	SetLogger(logger)
}

func CreateAdapter(requiresAuth bool, opts ...adpt.Option) (adapter *adpt.Adapter) {
	return CreateAdapterWithTimeout(requiresAuth, timeout, opts...)
}

// Returns an HTTP adapter which will wait a max. of `timeoutSec` sec for a reply.
// It also pre-configures the adapter in the following way:
//
//   - If `requiresAuth` is set, each outgoing request includes an `Authorization` header
//     with a 'Bearer' token provided either via the `--access-token` flag,
//     the IVCAP_ACCESS_TOKEN environment, or the AccessToken from the ActiveContext.
//   - If the `path` parameter for any of the adapter calls is NOT a fully fledged URL,
//     the URL defined in ActiveContext is automatically prefixed.
//   - If the ActiveContext defines a `Host` parameter, it is also added as a
//     `Host` HTTP header.
func CreateAdapterWithTimeout(requiresAuth bool, timeoutSec int, opts ...adpt.Option) (adapter *adpt.Adapter) {
	ctxt := GetActiveContext() // will always return with a context

	if requiresAuth {
		if accessToken == "" {
			accessToken = getAccessToken(true)
		}
		if accessToken == "" {
			cobra.CheckErr(
				fmt.Sprintf("Adapter requires auth token. Set with '--access-token' or env '%s'", ACCESS_TOKEN_ENV))
		}
	}

	url := ctxt.URL
	var headers *map[string]string
	if ctxt.Host != "" {
		headers = &(map[string]string{"Host": ctxt.Host})
	}
	logger.Debug("Adapter config", log.String("url", url))

	adp, err := NewAdapter(url, accessToken, timeoutSec, headers, opts...)
	if adp == nil || err != nil {
		cobra.CheckErr(fmt.Sprintf("cannot create adapter for '%s' - %s", url, err))
	}
	return adp
}

// ****** ADAPTER ****

func NewAdapter(
	url string,
	accessToken string,
	timeoutSec int,
	headers *map[string]string,
	opts ...adpt.Option,
) (*adpt.Adapter, error) {
	options := []adpt.Option{
		adpt.WithConnContext(&adpt.ConnectionCtxt{
			URL: url, AccessToken: accessToken, TimeoutSec: timeoutSec, Headers: headers,
		}),
	}
	options = append(options, opts...)
	adapter := adpt.RestAdapter(options...)
	return &adapter, nil
}

func NewTimeoutContext() (ctxt context.Context, cancel context.CancelFunc) {
	to := time.Now().Add(time.Duration(timeout) * time.Second)
	// #nosec G118 - cancel is returned to and managed by the caller
	ctxt, cancel = context.WithDeadline(context.Background(), to)
	return
}

func Logger() *log.Logger {
	return logger
}

func SetLogger(l *log.Logger) {
	logger = l
}

func safeString(s *string) string {
	if s != nil {
		return *s
	}
	return ""
}

func safeDate(s *string, humanizeOnly bool) string {
	if s != nil {
		t, err := time.Parse(time.RFC3339, *s)
		if err != nil {
			// fmt.Println("Error while parsing date :", err)
			return *s
		}
		h := humanize.Time(t)
		if humanizeOnly {
			return h
		} else {
			return fmt.Sprintf("%s (%s)", h, t.Local().Format(time.RFC822))
		}
	} else {
		return "???"
	}
}

func safeTruncString(in *string) (out string) {
	if in != nil {
		out = *in
	} else {
		out = "???"
	}
	if len(out) > MAX_NAME_COL_LEN {
		out = out[0:MAX_NAME_COL_LEN-3] + "..."
	}
	return
}

func safeBytes(n *int64) string {
	if n == nil {
		return "???"
	}
	if *n <= 0 {
		return "unknown"
	}
	// Safe to convert to uint64 here because we've checked for negative values
	// #nosec G115
	return humanize.Bytes(uint64(*n))
}

func payloadFromFile(fileName string, inputFormat string) (pyld adpt.Payload, err error) {
	isYaml := inputFormat == "yaml" || strings.HasSuffix(fileName, ".yaml") || strings.HasSuffix(fileName, ".yml")
	if fileName != "-" {
		pyld, err = adpt.LoadPayloadFromFile(fileName, isYaml)
	} else {
		pyld, err = adpt.LoadPayloadFromStdin(isYaml)
	}
	return
}

// ***** CHECK FOR NEWER VERSIONS

func checkForUpdates(currentVersion string) {
	path := makeConfigFilePath(VERSION_CHECK_FILE_NAME)
	if data, err := os.ReadFile(filepath.Clean(path)); err == nil {
		if lastCheck, err := time.Parse(time.RFC3339, string(data)); err == nil {
			d := time.Since(lastCheck)
			// fmt.Printf(".... since: %d < %d - %s\n", d, CHECK_VERSION_INTERVAL, path)
			if d < CHECK_VERSION_INTERVAL {
				// too soon
				return
			}
		} else {
			logger.Debug("cannot parse data in version check file", log.Error(err))
		}
	}

	// check latest versionpath string
	client := &http.Client{
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
	if resp, err := client.Head(RELEASE_CHECK_URL); err != nil {
		logger.Debug("checkForUpdates: while checking github", log.Error(err))
	} else {
		if loc, err := resp.Location(); err != nil {
			logger.Debug("checkForUpdates: while getting location", log.Error(err))
		} else {
			p := strings.Split(loc.Path, "/")
			latest := strings.TrimPrefix(p[len(p)-1], "v")
			current := strings.TrimPrefix(strings.Split(currentVersion, "|")[0], "v")
			if current != latest {
				fmt.Fprintf(os.Stderr, "\n>>>   A newer version 'v%s' is available. Please consider upgrading from 'v%s'", latest, current)
				fmt.Fprintf(os.Stderr, "\n>>>     It is available at %s", RELEASE_CHECK_URL)
				fmt.Fprintf(os.Stderr, "\n>>>     Or via 'brew upgrade ivcap'\n\n")
			}
		}
	}

	ts := time.Now().Format(time.RFC3339)
	if err := os.WriteFile(path, []byte(ts), fs.FileMode(0600)); err != nil {
		logger.Debug("cannot write version check timestamp", log.Error(err))
	}
}

func addNextPageRow(
	nextPage *string,
	pIn []table.Row,
) (pOut []table.Row) {
	if nextPage == nil {
		return pIn
	}
	u, err := url.Parse(*nextPage)
	if err == nil {
		page := u.Query().Get("page")
		pOut = pIn
		pOut = append(pOut, table.Row{"... " + MakeHistory(&page)})
	}
	return
}
